#!/bin/bash

# Setup script for local Lambda debugging
# This script creates .env.local files from Terraform outputs

set -e

echo "🔧 Setting up local Lambda debugging environment"
echo "================================================"
echo ""

# Check if terraform is available
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found. Please install Terraform first."
    exit 1
fi

# Check if we're in the right directory
if [ ! -d "cloud/infra" ]; then
    echo "❌ Please run this script from the project root directory"
    exit 1
fi

# Get Terraform outputs
echo "📊 Getting Terraform outputs..."
cd cloud/infra

RAW_BUCKET=$(terraform output -raw raw_audio_bucket_name 2>/dev/null || echo "")
TRANSCRIPTS_BUCKET=$(terraform output -raw transcripts_bucket_name 2>/dev/null || echo "")
DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name 2>/dev/null || echo "")
SQS_QUEUE_URL=$(terraform output -raw sqs_queue_url 2>/dev/null || echo "")
API_KEY=$(terraform output -raw api_key 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")

cd ../..

if [ -z "$RAW_BUCKET" ]; then
    echo "❌ Failed to get Terraform outputs. Make sure infrastructure is deployed."
    exit 1
fi

echo "✅ Got Terraform outputs"
echo ""

# Create .env.local for ingest-audio
echo "📝 Creating .env.local for ingest-audio..."
cat > cloud/lambdas/ingest-audio/.env.local <<EOF
# Auto-generated by setup-lambda-debug.sh
# AWS Credentials (using default AWS profile)
AWS_REGION=${AWS_REGION}

# Lambda Environment Variables
RAW_AUDIO_BUCKET=${RAW_BUCKET}
DYNAMODB_TABLE=${DYNAMODB_TABLE}
USER_ID=test-user
API_KEY=${API_KEY}
EOF

echo "✅ Created cloud/lambdas/ingest-audio/.env.local"

# Create .env.local for transcription-dispatcher
echo "📝 Creating .env.local for transcription-dispatcher..."
cat > cloud/lambdas/transcription-dispatcher/.env.local <<EOF
# Auto-generated by setup-lambda-debug.sh
# AWS Credentials (using default AWS profile)
AWS_REGION=${AWS_REGION}

# Lambda Environment Variables
RAW_AUDIO_BUCKET=${RAW_BUCKET}
DYNAMODB_TABLE=${DYNAMODB_TABLE}
SQS_QUEUE_URL=${SQS_QUEUE_URL}
USER_ID=test-user
EOF

echo "✅ Created cloud/lambdas/transcription-dispatcher/.env.local"

# Create .env.local for query-transcripts
echo "📝 Creating .env.local for query-transcripts..."
cat > cloud/lambdas/query-transcripts/.env.local <<EOF
# Auto-generated by setup-lambda-debug.sh
# AWS Credentials (using default AWS profile)
AWS_REGION=${AWS_REGION}

# Lambda Environment Variables
DYNAMODB_TABLE=${DYNAMODB_TABLE}
TRANSCRIPTS_BUCKET=${TRANSCRIPTS_BUCKET}
USER_ID=test-user
EOF

echo "✅ Created cloud/lambdas/query-transcripts/.env.local"

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Next steps:"
echo "1. Install dependencies:"
echo "   cd cloud/lambdas/ingest-audio && npm install"
echo "   cd cloud/lambdas/transcription-dispatcher && npm install"
echo "   cd cloud/lambdas/query-transcripts && npm install"
echo ""
echo "2. Run a Lambda locally:"
echo "   cd cloud/lambdas/ingest-audio"
echo "   npm run dev /path/to/test.wav"
echo ""
echo "3. Debug with VS Code:"
echo "   cd cloud/lambdas/ingest-audio"
echo "   npm run debug"
echo "   Then attach VS Code debugger (F5)"
echo ""
echo "📚 See cloud/lambdas/README-LOCAL-DEBUG.md for full documentation"

