#!/bin/bash

# REM System - GPU Worker .env Setup Script
# This script reads Terraform outputs and creates the .env file for the GPU worker

set -e

echo "🔧 Setting up GPU Worker .env file"
echo "===================================="
echo ""

# Check if we're in the right directory
if [ ! -f "cloud/infra/main.tf" ]; then
  echo "❌ Error: Please run this script from the project root directory"
  exit 1
fi

# Get Terraform outputs
echo "📋 Reading Terraform outputs..."
cd cloud/infra

if [ ! -f "terraform.tfstate" ]; then
  echo "❌ Error: Terraform state not found. Have you run 'terraform apply'?"
  exit 1
fi

SQS_QUEUE_URL=$(terraform output -raw sqs_queue_url 2>/dev/null || echo "")
RAW_AUDIO_BUCKET=$(terraform output -raw raw_audio_bucket_name 2>/dev/null || echo "")
TRANSCRIPTS_BUCKET=$(terraform output -raw transcripts_bucket_name 2>/dev/null || echo "")
DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name 2>/dev/null || echo "")

cd ../..

# Validate outputs
if [ -z "$SQS_QUEUE_URL" ] || [ -z "$RAW_AUDIO_BUCKET" ] || [ -z "$TRANSCRIPTS_BUCKET" ] || [ -z "$DYNAMODB_TABLE" ]; then
  echo "❌ Error: Could not read all required Terraform outputs"
  echo "Make sure Terraform has been applied successfully"
  exit 1
fi

echo "✅ Terraform outputs read successfully"
echo ""

# Create .env file
ENV_FILE="cloud/gpu-worker/.env"

echo "📝 Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# REM GPU Worker Configuration
# Auto-generated by setup-gpu-worker-env.sh
# Generated: $(date)

# AWS Configuration
AWS_REGION=us-east-1
# If using AWS CLI configured credentials, comment out these lines:
# AWS_ACCESS_KEY_ID=your-access-key-id
# AWS_SECRET_ACCESS_KEY=your-secret-access-key

# SQS Queue (from Terraform output)
SQS_QUEUE_URL=$SQS_QUEUE_URL

# S3 Buckets (from Terraform output)
RAW_AUDIO_BUCKET=$RAW_AUDIO_BUCKET
TRANSCRIPTS_BUCKET=$TRANSCRIPTS_BUCKET

# DynamoDB Table (from Terraform output)
DYNAMODB_TABLE=$DYNAMODB_TABLE

# Whisper Configuration
WHISPER_MODEL=base
# Options: tiny, base, small, medium, large-v2, large-v3
# Larger models are more accurate but slower and require more VRAM

WHISPER_DEVICE=cpu
# Options: cuda, cpu
# Use 'cuda' for GPU acceleration, 'cpu' for CPU-only

WHISPER_COMPUTE_TYPE=float32
# Options: float16, int8, float32
# float16 is fastest on GPU, int8 for lower memory, float32 for CPU

# Worker Configuration
POLL_INTERVAL=5
# Seconds to wait between SQS polls when queue is empty

MAX_MESSAGES=1
# Number of messages to process in parallel (be careful with GPU memory)

VISIBILITY_TIMEOUT=900
# SQS visibility timeout in seconds (should match Terraform config)

# Logging
LOG_LEVEL=INFO
# Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
EOF

echo "✅ .env file created successfully"
echo ""
echo "📋 Configuration:"
echo "  SQS Queue: $SQS_QUEUE_URL"
echo "  Raw Audio Bucket: $RAW_AUDIO_BUCKET"
echo "  Transcripts Bucket: $TRANSCRIPTS_BUCKET"
echo "  DynamoDB Table: $DYNAMODB_TABLE"
echo ""
echo "🎉 GPU Worker is ready!"
echo ""
echo "Next steps:"
echo "  1. Review and edit $ENV_FILE if needed"
echo "  2. If you have a GPU, change WHISPER_DEVICE=cuda"
echo "  3. Run: make run-worker"
echo ""

